// Generated by ReScript, PLEASE EDIT WITH CARE


let BackButton = {};

let BottomButton = {};

let SettingsButton = {};

let HapticFeedback = {};

let CloudStorage = {};

let BiometricManager = {};

let Accelerometer = {};

let DeviceOrientation = {};

let Gyroscope = {};

let LocationManager = {};

let DeviceStorage = {};

let SecureStorage = {};

let Global = {};

let Events = {};

export {
  BackButton,
  BottomButton,
  SettingsButton,
  HapticFeedback,
  CloudStorage,
  BiometricManager,
  Accelerometer,
  DeviceOrientation,
  Gyroscope,
  LocationManager,
  DeviceStorage,
  SecureStorage,
  Global,
  Events,
}
/* No side effect */
