// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

console.log(window.Telegram.WebApp.version, window.Telegram.WebApp.platform);

let chat = window.Telegram.WebApp.initDataUnsafe.chat;

let greeting = chat !== undefined ? "This is " + chat.title : "No current chat";

if (window.Telegram.WebApp.isActve && window.Telegram.WebApp.isExpanded) {
  console.log("Live and active");
}

window.Telegram.WebApp.requestFullscreen();

function onFullscreenChange() {
  if (window.Telegram.WebApp.isFullscreen) {
    console.log("Fullscreen on");
  } else {
    console.log("Fullscreen off");
  }
}

window.Telegram.WebApp.onEvent("fullscreenChanged", onFullscreenChange);

window.Telegram.WebApp.offEvent("fullscreenChanged", onFullscreenChange);

function onShareMessageFailed(event) {
  let message = event.error;
  if (message === "UNSUPPORTED" || message === "UNKNOWN_ERROR" || message === "MESSAGE_EXPIRED" || message === "USER_DECLINED" || message === "MESSAGE_SEND_FAILED") {
    switch (message) {
      case "UNSUPPORTED" :
        console.log("Sharing messages is not supported by client");
        return;
      case "MESSAGE_EXPIRED" :
        console.log("The message is expired");
        return;
      case "MESSAGE_SEND_FAILED" :
        console.log("Failed to send. Retry?");
        return;
      case "USER_DECLINED" :
        console.log("Aborted by the user");
        return;
      case "UNKNOWN_ERROR" :
        console.log("Something mysterious");
        return;
    }
  } else {
    console.log("Undocumented error: " + message);
    return;
  }
}

window.Telegram.WebApp.onEvent("shareMessageFailed", onShareMessageFailed);

window.Telegram.WebApp.offEvent("shareMessageFailed", onShareMessageFailed);

if (window.Telegram.WebApp.BackButton.isVisible) {
  console.log("The back button is on");
}

window.Telegram.WebApp.BackButton.show().hide();

window.Telegram.WebApp.BackButton.isVisible = true;

window.Telegram.WebApp.MainButton.enable().setText("Press Me").onClick(() => {
  console.log("hello");
}).show();

window.Telegram.WebApp.DeviceStorage.setItem("StoredKey", "StoredValue", (error, value) => {
  if (error === null) {
    if (value !== undefined) {
      if (value) {
        console.log("Item successfuly stored");
      } else {
        console.log("Failed to store item");
      }
    } else {
      console.error("Invalid arguments!");
    }
    return;
  }
  if (error === "UNKNOWN_ERROR") {
    console.log("Unknown error occured");
    return;
  }
  console.log("New type of error: " + error);
});

let InvalidCallbackArguments = /* @__PURE__ */Primitive_exceptions.create("TelegramWebApp__test.InvalidCallbackArguments");

function toResult(error, value) {
  if (error !== null) {
    return {
      TAG: "Error",
      _0: error
    };
  }
  if (value !== undefined) {
    return {
      TAG: "Ok",
      _0: Primitive_option.valFromOption(value)
    };
  }
  throw {
    RE_EXN_ID: InvalidCallbackArguments,
    Error: new Error()
  };
}

window.Telegram.WebApp.DeviceStorage.setItem("StoredKey", "StoredValue", (error, value) => {
  let match = toResult(error, value);
  if (match.TAG === "Ok") {
    if (match._0) {
      console.log("Item successfuly stored");
    } else {
      console.log("Failed to store item");
    }
    return;
  }
  let message = match._0;
  if (message === "UNKNOWN_ERROR") {
    console.log("Unknown error occured");
    return;
  }
  console.log("New type of error discovered: " + message);
});

console.log(someOtherGlobalValue.version);

export {
  greeting,
  onFullscreenChange,
  onShareMessageFailed,
  InvalidCallbackArguments,
  toResult,
}
/*  Not a pure module */
